# CHAT_BACKEND

apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  BACKEND_URL: "/chat-backend"
  REDIS_URL: "redis-service:6379"

---

# MYSQL_JOOMLA

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ROOT_PASSWORD: parola_root
  MYSQL_DATABASE : pizzeria_db
  MYSQL_USER : joomla
  MYSQL_PASSWORD : parola_joomla

---

# IA_BACKEND

apiVersion: v1
kind: ConfigMap
metadata:
  name: ia-backend-config
data:
  container-name: "audio-files"
  speech-region: "canadacentral"



