apiVersion: v1
kind: Secret
metadata:
  name: ia-backend-secrets
type: Opaque
stringData:
  connection-string: "Server=tcp:proiect-ia-server.database.windows.net,1433;Initial Catalog=IA_database;Persist Security Info=False;User ID=dbadmin;Password=admin2025!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  blob-connection-string: "DefaultEndpointsProtocol=https;AccountName=proiectstorageia;AccountKey=NJOLD+US0L7POPfSnkOphoAEDK8aS0TMVIxJOUP3f1YNtMlwly2WugZazDq674J89ZoWzuGUwFME+AStbpkeVw==;EndpointSuffix=core.windows.net"
  speech-key: "3xLxwxcyAx8H8Aop70Ih2qIqL5rSrOkgDA49s8oUQstpEzDvWISDJQQJ99BDACBsN54XJ3w3AAAYACOGnmSg"