apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  JOOMLA_DB_PASSWORD: cGFyb2xhX2pvb21sYQ==
  JOOMLA_DB_USER: am9vbWxh
  JOOMLA_DB_NAME: cGl6emVyaWFfZGI=
  JOOMLA_DB_HOST: ZGI=
