version: '3.8'

services:
  # Backend și Nginx combinate într-un singur container
  chat-backend:
    build: 
      context: ./chat-backend
      dockerfile: Dockerfile
    ports:
      - "88:80"  # expunem Nginx pe portul 88 extern
    depends_on:
      - mongodb
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
    networks:
      - chat-network

  # Frontend - Aplicația React
  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    ports:
      - "90:90"
    environment:
      - REACT_APP_API_URL=http://localhost:88
      - REACT_APP_SIGNALR_HUB_URL=http://localhost:88/chatHub
      - PORT=90
    depends_on:
      - chat-backend
    networks:
      - chat-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
