version: '3.8'

services:
  chatserver:
    build: 
      context: ./chat-backend
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - mongodb
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - ASPNETCORE_URLS=http://+:80
    networks:
      - chat-network
  nginx:
    image: nginx:latest
    ports:
      - "88:80"  # expunem Nginx pe portul 88
    volumes:
      - ./chat-backend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chatserver
    networks:
      - chat-network

   # Frontend - Aplicația React
  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    ports:
      - "90:90"
    depends_on:
      - nginx
    networks:
      - chat-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb-data: