apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
        - name: joomla
          image: floreagabriel/joomla:latest
          ports:
            - containerPort: 80
          env:
            - name: JOOMLA_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JOOMLA_DB_HOST

            - name: JOOMLA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JOOMLA_DB_PASSWORD

            - name: JOOMLA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JOOMLA_DB_USER

            - name: JOOMLA_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JOOMLA_DB_NAME

            - name: JOOMLA_DB_TYPE
              value: "mysqli"
