apiVersion: v1
kind: ConfigMap
metadata:
  name: ia-backend-config
data:
  AzureSpeechService__Region: "canadacentral"
  AzureBlobStorage__ContainerName: "audio-files"
  ASPNETCORE_ENVIRONMENT: "Production"