apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: floreagabriel/chat-backend
        ports:
        - containerPort: 80
        env:
        - name: MongoDbSettings__ConnectionString
          valueFrom:
            secretKeyRef: 
              name: mongodb-credentials
              key: connection_string
        - name: MongoDbSettings__DatabaseName
          valueFrom:
            configMapKeyRef:
              name: chat-backend-config
              key: MongoDbSettings__DatabaseName
        - name: MongoDbSettings__MessagesCollectionName
          valueFrom:
            configMapKeyRef:
              name: chat-backend-config
              key: MongoDbSettings__MessagesCollectionName
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef: 
              name: chat-backend-config
              key: ASPNETCORE_URLS
      
