apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: floreagabriel/chat-backend
        ports:
        - containerPort: 80  # Nginx expune portul 80, aplicația .NET rulează pe 5000 intern
        env:
        - name: MongoDbSettings__ConnectionString
          value: mongodb://mongodb-service:27017
        - name: ASPNETCORE_URLS
          value: http://+:5000  # Aplicația .NET rulează pe portul 5000 intern

